export default [
  {
    "product_handle": "brushed-legging",
    "state": "published",
    "rating": 5,
    "title": "loved them",
    "author": "Ana L.",
    "email": "analatorreluy@hotmail.com",
    "location": "United States",
    "body": "They are soft, comfortable, and overall great fit",
    "reply": "",
    "created_at": "2017-11-13 14:36:33 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "brushed-midi",
    "state": "published",
    "rating": 5,
    "title": "So soft and comfortable!",
    "author": "Danielle R.",
    "email": "danielleradulskiyoga@gmail.com",
    "location": "United States",
    "body": "Loved them! Especially the leggings =)",
    "reply": "",
    "created_at": "2017-11-14 10:23:54 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "brushed-midi",
    "state": "published",
    "rating": 5,
    "title": "Brushed Midi",
    "author": "Lindsey K.",
    "email": "lindseykeath@gmail.com",
    "location": "United States",
    "body": "Amazingly light weight comfortable and fits perfectly I will definitely be ordering another",
    "reply": "",
    "created_at": "2017-11-15 07:48:46 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "scuba-zip-hoodie",
    "state": "published",
    "rating": 5,
    "title": "Love it!",
    "author": "Juliana S.",
    "email": "julisylvia@gmail.com",
    "location": "United States",
    "body": "Love my scuba zip hoodie! It's warm for a run on a crisp morning also super easy to layer if colder weather. Love that it has a hood too. The fabric is soft.",
    "reply": "",
    "created_at": "2017-11-27 20:43:09 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-legging",
    "state": "published",
    "rating": 5,
    "title": "Love these leggings!",
    "author": "Janise H.",
    "email": "janise_ho@yahoo.com",
    "location": "United States",
    "body": "These are my most comfortable pair of gym leggings. They are so soft and stretchy. The fleece inside is perfect for winter. Would definitely recommend",
    "reply": "",
    "created_at": "2017-11-28 16:08:42 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "scuba-pullover",
    "state": "published",
    "rating": 5,
    "title": "Love the style and fit!",
    "author": "Kelly W.",
    "email": "kellyweng88@gmail.com",
    "location": "United States",
    "body": "Not going to lie, feel like I look pretty badass in this. I wear this whenever I want to be comfortable or need a confidence boost. I have black too. Love it!",
    "reply": "",
    "created_at": "2017-11-28 21:35:32 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-tee",
    "state": "published",
    "rating": 5,
    "title": "Pretty comfortable and lightweight, the",
    "author": "Sarah G.",
    "email": "skg898@gmail.com",
    "location": "United States",
    "body": "Pretty comfortable and lightweight, the box cut out detail has kept me nice and cool in hot temperatures!",
    "reply": "",
    "created_at": "2017-11-28 21:44:51 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-legging",
    "state": "published",
    "rating": 5,
    "title": "Most comfy leggings I’ve ever owned",
    "author": "angela f.",
    "email": "afernan89@gmail.com",
    "location": "United States",
    "body": "These leggings fit great (although i wished they were a little longer, I’m 5’9”) but besides that, I love these. They are also warm which is a plus for me since I like to wear leggings in the winter!",
    "reply": "",
    "created_at": "2017-11-29 11:42:09 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-legging",
    "state": "approved",
    "rating": 4,
    "title": "Quality, comfortable leggings",
    "author": "Fanny C.",
    "email": "fanny_chan@fitnyc.edu",
    "location": "United States",
    "body": "Quality, good material - bought their black leggings w/ the perforated detail around the calves. Very stylish and comfortable for both gym and casual wear. It's also good for colder weathers since it's fleece-lined. That was an unexpected, pleasant surprise to the fabric! Will keep tabs on this brand for more, different styles in the future.",
    "reply": "",
    "created_at": "2017-11-29 11:57:09 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-tank",
    "state": "published",
    "rating": 5,
    "title": "Great design and fit",
    "author": "hester f.",
    "email": "funghester@gmail.com",
    "location": "United States",
    "body": "Great design and fit, would love to see it with a racerback.",
    "reply": "",
    "created_at": "2017-11-29 20:11:26 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "light-scuba-hoodie",
    "state": "published",
    "rating": 5,
    "title": "Obsessed with this hoodie!",
    "author": "Sylvie C.",
    "email": "sylvie.curci@gmail.com",
    "location": "United States",
    "body": "Absolutely love it. So flattering. Get so many compliments on it!",
    "reply": "",
    "created_at": "2018-01-03 16:25:28 -0500",
    "replied_at": ""
  },
  {
    "product_handle": "box-out-legging",
    "state": "published",
    "rating": 5,
    "title": "Great material and very flattering!!",
    "author": "Sasha V.",
    "email": "svos19@gmail.com",
    "location": "United States",
    "body": "My overall experience was great",
    "reply": "",
    "created_at": "2018-01-12 10:08:08 -0500",
    "replied_at": ""
  }
]